import { Manrope } from "next/font/google";
import "./globals.css";

const manropeSans = Manrope({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${manropeSans.variable} antialiased`}>{children}</body>
		</html>
	);
}
